# Generated by Django 3.1.5 on 2021-01-31 06:11

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import project.phone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFlatRoof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('about_info', models.TextField(blank=True, null=True, verbose_name='О представленой информации')),
            ],
            options={
                'verbose_name': 'Блок выгода',
            },
        ),
        migrations.CreateModel(
            name='InfoCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название компании')),
                ('phone', project.phone.PhoneField(verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=150, verbose_name='Почта')),
                ('open_time', models.TimeField(verbose_name='Работаем с')),
                ('close_time', models.TimeField(verbose_name='Работаем по')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на инстаграм')),
                ('youtube', models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на ютюб')),
            ],
            options={
                'verbose_name': 'Основная информация компании',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='main_block/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Основной блок',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex', models.TextField(blank=True, null=True, verbose_name='Яндекс метрика')),
            ],
            options={
                'verbose_name': 'Метрики для сайта',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.TextField(verbose_name='Описание картинки - АЛЬТ')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='portfolio/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блок наши работы, портфолио',
            },
        ),
        migrations.CreateModel(
            name='ProfitBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Блок выгода',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок сайта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'Сео для сайта',
            },
        ),
        migrations.CreateModel(
            name='WorkPriceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100, verbose_name='Название работы')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='price_images/', verbose_name='Изображение')),
                ('block_float_roof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='float_prices', to='home.blockflatroof', verbose_name='Блок с ценами')),
            ],
            options={
                'verbose_name': 'Работа с ценой',
                'verbose_name_plural': 'Работа с ценой',
            },
        ),
    ]
