# Generated by Django 3.1.5 on 2021-01-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSlopRoof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('about_info', models.TextField(blank=True, null=True, verbose_name='О представленой информации')),
            ],
            options={
                'verbose_name': 'Блок c ценами, скатная крыша',
            },
        ),
        migrations.AlterModelOptions(
            name='blockflatroof',
            options={'verbose_name': 'Блок c ценами, плоская крыша'},
        ),
        migrations.AlterField(
            model_name='workpriceimage',
            name='block_float_roof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='float_prices', to='home.blockflatroof', verbose_name='Блок с ценой'),
        ),
        migrations.AddField(
            model_name='workpriceimage',
            name='block_slop_roof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slop_prices', to='home.blocksloproof', verbose_name='Блок с ценой'),
        ),
    ]
