# Generated by Django 3.1.5 on 2021-01-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210131_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockflatroof',
            options={'verbose_name': 'Блок - Цены, плоская крыша'},
        ),
        migrations.AlterModelOptions(
            name='blocksloproof',
            options={'verbose_name': 'Блок - Цены, скатная крыша'},
        ),
        migrations.AlterModelOptions(
            name='mainblock',
            options={'verbose_name': 'Блок - Основной'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Блок - Наши работы'},
        ),
        migrations.AlterModelOptions(
            name='profitblock',
            options={'verbose_name': 'Блок - Выгода'},
        ),
    ]
