# Generated by Django 3.1.5 on 2021-01-31 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210131_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Блок - Наши работы', 'verbose_name_plural': 'Блок - Наши работы'},
        ),
    ]
