# Generated by Django 3.1.5 on 2021-01-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210131_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocompany',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Работаем по'),
        ),
        migrations.AlterField(
            model_name='infocompany',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Работаем с'),
        ),
    ]
