# Generated by Django 3.1.5 on 2021-01-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210131_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainblock',
            name='alt',
            field=models.TextField(default='', verbose_name='Описание картинки - АЛЬТ'),
            preserve_default=False,
        ),
    ]
