# Generated by Django 3.1.5 on 2021-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210131_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова'),
        ),
    ]
