# Generated by Django 3.1.5 on 2021-02-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_seo_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('video_youtube', models.CharField(max_length=200, verbose_name='Ссылка на видео на Youtube')),
            ],
            options={
                'verbose_name': 'Блок - обо мне',
            },
        ),
    ]
