# Generated by Django 3.1.5 on 2021-02-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutmeblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmeblock',
            options={'verbose_name': 'Блок - Обо мне'},
        ),
    ]
