# Generated by Django 3.1.5 on 2021-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210201_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeblock',
            name='caption',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutmeblock',
            name='video_youtube',
            field=models.CharField(max_length=250, verbose_name='Ссылка на видео на Youtube'),
        ),
    ]
