# Generated by Django 3.1.5 on 2021-02-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210201_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmeblock',
            name='video_youtube',
        ),
        migrations.AddField(
            model_name='aboutmeblock',
            name='frame_youtube',
            field=models.TextField(default='', verbose_name='Код frame для видео с Youtube'),
            preserve_default=False,
        ),
    ]
